### ISSUE TITLE
 #1364 - Field 'mda' doesn't have a default value

### ISSUE THREAD

**Issue by internethering** [PF4Public/fetchmail#2]
Hi, saving to database doesn't work. Roundcube log (level 8) says:

```
Apr 13 21:52:48 hetzner roundcube[32489]: <ph4bktic> Warning: Call to deprecated function get_input_value(); See bc.inc for replacement
Apr 13 21:52:48 hetzner roundcube[32489]: <ph4bktic> [4] SELECT * FROM fetchmail WHERE mailbox='local@domain.tld';
Apr 13 21:52:48 hetzner roundcube[32489]: <ph4bktic> [5] INSERT INTO fetchmail (mailbox, active, src_server, src_user, src_password, src_folder, poll_time, fetchall, keep, protocol, usessl, src_auth) VALUES ('local@domain.tld', '1', 'imap.example.com', 'local@example.com', '<password>', '', '10', '0', '1', 'imap', '1', 'password' );
Apr 13 21:52:48 hetzner roundcube[32489]: <ph4bktic> Warning: Call to deprecated function rep_specialchars_output(); See bc.inc for replacement
Apr 13 21:52:48 hetzner roundcube[32489]: <ph4bktic> [6] SELECT * FROM fetchmail WHERE mailbox='local@domain.tld';
```

I tested the INSERT-Statement manuall, MySQL says:

>  #1364 - Field 'mda' doesn't have a default value

INSERT-Statement should be:

`INSERT INTO fetchmail (mailbox, active, src_server, src_user, src_password, src_folder, poll_time, fetchall, keep, protocol, usessl, src_auth, mda) VALUES ('local@domain.tld', '1', 'imap.example.com', 'local@example.com', '<password>', '', '10', '0', '1', 'imap', '1', 'password', '' )`

**Comment by PF4Public** [comment]
True, postgres and mysql schemas differ, so that I could not catch this earlier. :(
I guess only mysql users are affected
Please, anyone affected perform this query on your fetchmail table and see if that fixes the issue without editing fetchmail.php:
`ALTER TABLE fetchmail CHANGE `mda` `mda` varchar(255) NOT NULL DEFAULT ''`

PS: I'd like to edit your report to make validation issue a separate bug, if you don't mind.

**Comment by internethering** [comment]
I've no problem with productive edits :)
