### ISSUE TITLE
MySQL-Datenbank auswählen

### ISSUE THREAD

**Issue by volker-raschek** [PF4Public/fetchmail#20]
Hallo zusammen,
das Plugin ist eine sehr tolle Sache. Allerdings würde ich mir wünschen, man könnte mehr Konfigurationseinstellungen anpassen.

Ich betreibe einen Webserver mit Postfixadmin und dort wurden Einträge für fetchmail immer manuell hinterlegt. Somit liegen die Einträge in der Datenbank von postfixadmin in der Tabelle fetchmail. Das Plugin bietet zwar die Möglichkeit dem Benutzer selbst die Einstellungen an zu passen allerdings möchte man die Daten gerne in einer gemeinsamen Tabelle pflegen. Das Plugin bezieht sich hier allerdings ausschließlich auf die Datenbank von Roundcube. Die Datenbank von Roundcube und Postfixadmin sind allerdings eigenständige.

Wäre es möglich das Skript so an zu passen über die Konfigurations-Parameter, in welcher Datenbank und mit welchem User + Passwort er auf die Tabelle fetchmail zugreift?

Dann könnte man für Postfixadmin und für dieses Plugin ein und die selbe Tabelle nutzen.

Viele Grüße
Volker

---

Dear together,
the Plugin is great, but I wish I can set more configuration setting.

I have an Apache2 Webserver with Postfixadmin as GUI for Postfix. Under the Menü fetchmail in the GUI from Postfixadmin, I added some Mail-Accounts to fetch mails from external Mail-Servers. The fetchmail settings are stored in the table "fetchmail" from the database "postfixadmin". I want to use one table to store the fetchmail settings for the plugin and the Postfixadmin GUI, but i cant change the Datebase, the database user, the user password and the table where the fetchmail settings are stored.

Please add the configuration parameters in the configfile from the plugin to change the location where the fetchmail settings are stored.

Regards
Volker

**Comment by PF4Public** [comment]
Hello
As it is written in readme file, it is relatively easy to achieve this with PostgreSQL schemas, but I'm not certain if it is easily doable for MySQL.
I will examine the possibility of implementing this but neither can I guarantee this can be done at all, nor can I give you any time-estimates on the result of the check.
One of the reasons for not implementing this initially was the fact that any Roundcube plugin uses Roundcube API, which conveniently handles Database access. Doing this otherwise might break much of the code or require rewriting much of it, which is not the best idea.

**Comment by volker-raschek** [comment]
Hello, 
I use MySQL as Database. 

I would like to wish, if the team could implement this feature. I don't have another idea to resolve this problem to use one Database with one table of fetchmail settings for the roundcube plugin and the postfixadmin gui.

Regards 
Volker
