### ISSUE TITLE
mda

### ISSUE THREAD

**Issue by PF4Public** [PF4Public/fetchmail#8]
Allow setting `mda` field

**Comment by hoewer** [comment]
I use different MDA configurations for different mail accounts (different procmail scripts). Unfortunately these settings are overwritten by the plugin when saving. It would be nice to stop this behavior.
Of course it would be even better if one could configure the MDA for each individual mail account via the user interface.

**Comment by PF4Public** [comment]
Would you be able to implement it yourself and submit a PR?

**Comment by hoewer** [comment]
I haven't reviewed your code by now. Maybe I'm able to implement a change that reads the current mda from the database, and only changes this value if the global mda (config.inc.php) isn't empty. But it probably won't be very elegant, since I never dealt with php before. I guess I'll give it a try next week...

**Comment by PF4Public** [comment]
I would imagine it being possible if adding another variable: `$rcmail_config ['fetchmail_mda_editable'] = false;` which would control the ability for user to edit this variable.
